### ISSUE TITLE
Failure to render UI Controls on Remote Desktop Terminal Sessions (RDP)

### ISSUE THREAD

**Issue by ShadowMarker789** [MrJul/Estragonia#9] opened 2024-03-27 07:56 UTC
The Avalonian control does not render correctly on remote terminal services, even when a valid GPU adapter is available. 

I initially thought I was configuring it wrong, but it works fine on regular user sessions. 

If I repeatedly invalidate controls, I will occasionally get a flicker of the Avalonian content, but aside from that I see nothing from Avalonia. 

Estragonia on regular windows session

![image](https://github.com/MrJul/Estragonia/assets/37165910/4a724d18-6b4e-4a5b-8925-53f0c0f96d7b)

----

Estragonia on windows terminal session

![image](https://github.com/MrJul/Estragonia/assets/37165910/a689e8db-48d3-4b80-a367-727e5e027776)

Godot reports that a valid Vulkan device is present.

**Comment by ShadowMarker789** [comment] 2024-03-27 08:25
Beginning to diagnose this 

Drawing a line with the Skia context via Vulkan

Skia on WTS
![image](https://github.com/MrJul/Estragonia/assets/37165910/d1286242-6e1c-4feb-b5b4-feeb2ca99dc0)


----

Skia on normal session 
![image](https://github.com/MrJul/Estragonia/assets/37165910/9b47ccc3-cf23-4834-9f2b-7fcd6b31a1e1)

Isolated the issue to the Skia implementation in GodotSkiaGpu

**Comment by ShadowMarker789** [comment] 2024-03-27 09:35
Currently I'm suspecting something is going wrong with elements that are NOT redrawn constantly. 

Your hello world example seems to render, and it has animations. 

I get this on startup. 

![image](https://github.com/MrJul/Estragonia/assets/37165910/02787082-5fb1-460d-9604-ef82eba93453)

But then when I resize the window I do get the Avalonian content rendered. 

![image](https://github.com/MrJul/Estragonia/assets/37165910/5533b760-42ee-428c-8c7b-86e666f8c1e6)

Can you confirm whether you get issues for situations where all of the controls in Estragonia are not animated? 

I can alleviate the issue by having in _Process() calls to QueueRedraw in the User-Interface godot control.

**Comment by MrJul** [comment] 2024-03-28 11:33
Thank you for the report!

Is that an AMD GPU? If yes that's probably #5.
Currently, I can't reproduce with a remote RTX 4080.

**Comment by ShadowMarker789** [comment] 2024-03-29 09:19
> Thank you for the report!
> 
> Is that an AMD GPU? If yes that's probably #5. Currently, I can't reproduce with a remote RTX 4080.

Negative, that's an Nvidia Quadro P1000 on the work PC.

**Comment by MrJul** [comment] 2024-06-07 13:57
@ShadowMarker789 If possible, can you please try Estragonia 1.2.0-preview1 (targeting Godot 4.3-beta1)?

There have been efforts to fix the corruption on AMD GPU, and I believe the better Vulkan synchronization might have fixed this issue. (At least I can't see any issues on RDP sessions with both Nvidia and AMD GPUs.)

**Comment by MrJul** [comment] 2024-06-14 07:52
I'm closing this as potentially fixed in 1.2.0-preview1 - feel free to reopen if you can still reproduce the issue with that version.

**Closed by MrJul** 2024-06-14 07:52 UTC
Labels: bug
